### PR TITLE
LinkBench loader implementation

### PR DESCRIPTION
**Pull request by CSRessel**
Implemented based off of Facebook LinkBench loader ([mostly here](https://github.com/mdcallag/linkbench/blob/master/src/main/java/com/facebook/LinkBench/LinkBenchLoad.java)).

There is still a problem with the LinkBench DDL's -- I haven't been able to insert Node's without setting the data field to `mediumblob`, otherwise it claims the data is not valid utf-8, even after setting the table character set to utf8.

### CODE REVIEW

**Comment by CSRessel** [comment]
Exactly since the profile refactoring in 0c7d262 all database interactions during the loading have stopped having any effect; I'm currently working on pin-pointing the source of that problem.

**Comment by apavlo** [comment]
@CSRessel You can coordinate with @lmwnshn if you need help with this.

**Comment by CSRessel** [comment]
Three remaining tasks come to my mind:

1. What can be done to support the remaining test failure of linkbench on postgres?
2. Should the default constants for the linkbench loading be decreased so Travis runtime is approx. similar (at about 2 min for most tests except linkbench, which takes 11 min)?
3. What should the final type of the Node data column be @apavlo ? I tried setting the table character set to UTF8 and still had no luck.

Let me know what other changes should be made, for code quality or correctness or otherwise.

**Comment by lmwnshn** [comment]
There appear to be two main bugs with the test failure right now,

1. The procedures are written for MySQL syntax. To make it use Postgres syntax when running postgres, you can create a file at dialects/postgres-dialects.xml that will automagically replace it with the right thing. [example wikipedia postgres dialect](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/wikipedia/dialects/postgres-dialects.xml)

For example AddLink uses "ON DUPLICATE KEY UPDATE" and I don't think that's a thing in Postgres, it's [ON CONFLICT (..)](https://www.postgresql.org/docs/devel/static/sql-insert.html) something.

2. openjdk is again behaving differently from oraclejdk... I don't understand why openjdk would throw "PSQLException: Returning autogenerated keys is not supported." when oraclejdk doesn't. No clue for this one.

**Comment by CSRessel** [comment]
@lmwnshn I've added a `postgres-dialects.xml`, but am still receiving the failure for the "`ON DUPLICATE`" syntax. Is there anything else I need to do to enable the usage of these queries instead of the mysql ones?

As for the old testing environment, where did you find that version string? I didn't see anything like that in the Travis job log, and I don't know much else about the testing environment.

**Comment by lmwnshn** [comment]
Sorry, I haven't been on github for a while.

To my recollection, no. As long as you use the SQLStatement(...) classes, and set the right database type in the config, the magic will happen automatically.

I think I based my latter comment on https://github.com/oltpbenchmark/oltpbench/commit/3b8196a1af18536ffe71c5a743fdf17aa56fe a8d 

I can look at it this weekend.

**Pull request closed without merging**
