### PR TITLE
Add flag to collect sar data

### PR DESCRIPTION
**Pull request by mw2q**
This collects sar data for the load and execute steps.

### CODE REVIEW

**Comment by mw2q** [comment]
Is this a good way to collect system stats?

**Comment by apavlo** [comment]
I don't understand why this has to be embedded in the framework? Why not just run it as an external script?

**Comment by apavlo** [comment]
Actually this only runs on the client-side. You are assuming that the OLTP-Bench framework is running on the same machine as the DBMS. This is going to trip up a lot of people, so I think it's best to not add this flag.

**Comment by mw2q** [comment]
On 12/17/15 15:56, Andy Pavlo wrote:
> I don't understand why this has to be embedded in the framework? Why not just run it as an external script?

I think arguments can be made both ways, but perhaps the first thing I
need to understand is whether oltpbench agrees with with having system
stats collection as part of the framework?

**Comment by mw2q** [comment]
On 12/17/15 15:58, Andy Pavlo wrote:
> Actually this only runs on the client-side. You are assuming that the OLTP-Bench framework is running on the same machine as the DBMS. This is going to trip up a lot of people, so I think it's best to not add this flag.

Ah, I did overlook that.  I will close the pull request.

**Pull request closed without merging**
