### PR TITLE
sql related fixes to benchmarks - syntax, and case sensitive names

### PR DESCRIPTION
**Pull request by grooverdan**
hopefully fixes this error: https://travis-ci.org/grooverdan/oltpbench/jobs/213688254

### CODE REVIEW

**Comment by grooverdan** [comment]
sibench - fixes https://travis-ci.org/grooverdan/oltpbench/jobs/213688260

**Comment by grooverdan** [comment]
contention fix https://travis-ci.org/grooverdan/oltpbench/jobs/213688263

**Comment by grooverdan** [comment]
fix for linkbench error for non-mysql  https://travis-ci.org/grooverdan/oltpbench/jobs/213688267

**Comment by apavlo** [comment]
This all looks good. Let me know when you want me to merge.

**Comment by grooverdan** [comment]
yep. go for it. Doesn't fix all cases but its a start.

**Pull request merged**
